### ISSUE TITLE
is this code under active developement?

### ISSUE THREAD

**Issue by orgua** [Shagrat2/OneWireHub#1]
Hi @Shagrat2, 

do you plan on developing this lib any further? i made some commits in my fork. The main focus was to transform it into a proper/conformal library for the arduino library manager. I cleaned up the code and implemented some more functions on the way. The examples are up to date, but it breaks old code (because of changes like settemp() --> setTemp()). 

I like to keep working on this lib and i like to integrate it in the lib-manager-database.

Can i send you a pull request or should i decouple my fork?

**Comment by Shagrat2** [comment]
I finish use OneWire and goto to MySensors. Bat i wont develop future
Please make pull request

**Comment by Shagrat2** [comment]
I see you fork. It is good work. Thank you for job

**Comment by orgua** [comment]
thanks! yeah, at some point i noticed that it is easier to restart and make substantial changes to the design. for now it is growing. thanks for your groundwork
